//! Native plugin modules: an `import` whose target is a plugin library
//! (`plugins/math.so`) instead of a `.pp` file.
//!
//! The library's manifest (function names, signatures, Rust doc comments; see
//! `prepoly_plugin_host`) is turned into ordinary Prepoly source: one fully
//! annotated wrapper function per exposed function, carrying the doc comment,
//! whose body forwards to the `_plugin_call_*` / `_plugin_fcall_*` runtime
//! builtins with the library path, the function name, and the encoded
//! signature. Because the synthesized module is real source, the whole
//! front end -- type checking, visibility, hover, completion -- treats plugin
//! functions exactly like `.pp` functions.

use std::path::{Path, PathBuf};

use prepoly_plugin_host::ValueType;

/// The plugin library serving module path `segs` under `effective_root`, if
/// one exists: the last segment names the library file (`name.so` or the
/// `cdylib` output name `libname.so`, platform-suffixed), the leading
/// segments its directory. Also used by editor tooling to list a plugin
/// module's functions without loading the whole module graph.
pub fn plugin_library_for(effective_root: &Path, segs: &[String]) -> Option<PathBuf> {
    let (last, dir_segs) = segs.split_last()?;
    let mut dir = effective_root.to_path_buf();
    for s in dir_segs {
        dir.push(s);
    }
    prepoly_plugin_host::find_library(&dir, last)
}

/// Load the plugin at `lib` and synthesize its module source. Errors are
/// load-level (unreadable library, ABI mismatch, malformed manifest).
pub fn synthesize_plugin_module(lib: &Path) -> Result<String, String> {
    let manifest = prepoly_plugin_host::load_manifest(lib)?;
    // The runtime re-opens the library by this exact string; canonical form
    // keeps it stable regardless of the importing file's location.
    let lib_path = lib
        .canonicalize()
        .map_err(|e| format!("cannot resolve plugin path `{}`: {e}", lib.display()))?;
    let lib_str = lib_path.to_string_lossy();

    let mut src = format!(
        "// Native plugin module synthesized from `{lib_str}`.\n// Generated by the loader; the \
         functions below forward to the plugin.\n"
    );
    for f in &manifest.functions {
        src.push('\n');
        if let Some(doc) = &f.doc {
            // A `*/` inside the doc would close the comment early.
            src.push_str(&format!("/**\n{}\n*/\n", doc.replace("*/", "* /")));
        }
        let params = f
            .params
            .iter()
            .map(|(n, t)| format!("{}: {}", safe_param(n), prepoly_type(t)))
            .collect::<Vec<_>>()
            .join(", ");
        let args = f
            .params
            .iter()
            .map(|(n, _)| format!(", {}", safe_param(n)))
            .collect::<String>();
        let sig = sig_string(f);
        // Fallible functions return the builtin's `Result` whole, so the
        // wrapper is fallible; a fallible void return has no annotated form
        // and is left to return-type inference.
        let ret = match (f.fallible, &f.ret) {
            (_, ValueType::Void) => String::new(),
            (false, t) => format!(" -> {}", prepoly_type(t)),
            (true, t) => format!(" -> {}!", prepoly_type(t)),
        };
        let callee = format!(
            "_plugin_{}call_{}",
            if f.fallible { "f" } else { "" },
            f.ret.code()
        );
        let call = format!(
            "{callee}(\"{}\", \"{}\", \"{}\"{args})",
            escape(&lib_str),
            escape(&f.name),
            escape(&sig)
        );
        let body = if f.ret == ValueType::Void && !f.fallible {
            format!("    {call}\n")
        } else {
            format!("    return {call}\n")
        };
        src.push_str(&format!("fun {}({params}){ret} {{\n{body}}}\n", f.name));
    }
    Ok(src)
}

/// The manifest signature string of `f` (`"ii:i!"`), re-encoded for the
/// runtime call so argument marshaling needs no second manifest read.
fn sig_string(f: &prepoly_plugin_host::PluginFunction) -> String {
    let mut s = String::new();
    for (_, t) in &f.params {
        t.write_code(&mut s);
    }
    s.push(':');
    f.ret.write_code(&mut s);
    if f.fallible {
        s.push('!');
    }
    s
}

/// The Prepoly spelling of a plugin value type. An array is its element's
/// spelling with `[]` appended, so `Array(Array(Str))` reads `string[][]`.
fn prepoly_type(t: &ValueType) -> String {
    match t {
        ValueType::Void => "void".to_string(),
        ValueType::Bool => "bool".to_string(),
        ValueType::Int => "int64".to_string(),
        ValueType::Float => "float64".to_string(),
        ValueType::Str => "string".to_string(),
        ValueType::Bytes => "uint8[]".to_string(),
        ValueType::Array(elem) => format!("{}[]", prepoly_type(elem)),
    }
}

/// A parameter name safe to use in synthesized source: a Rust identifier that
/// collides with a Prepoly keyword gets a trailing `_`.
fn safe_param(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "fun", "type", "let", "const", "if", "else", "while", "for", "in", "return", "import",
        "match", "spawn", "true", "false", "null", "infer", "self", "Self", "mut", "ref", "error",
        "as", "break", "continue",
    ];
    if KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Escape a string for a synthesized Prepoly string literal.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
