#!/usr/bin/env python3
"""Regenerate the machine-generated benchmark programs in cases/.

The generated files are checked in; rerun this script only to re-scale the
corpus (adjust the size constants below), then re-run the benchmarks. Sizes
are chosen so that each case's slower pipeline lands roughly in the 0.3s-3s
range on a desktop machine.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
CASES = os.path.join(HERE, "cases")

WIDE_FNS = 300        # functions in the wide-program cases
CHAIN_LEN = 150       # depth of the unannotated-return call chain
BIG_MAIN_STMTS = 1200 # statements in the single-huge-main case


def wide_fn(name, i):
    """One synthetic function with a loop, branches, and mixed-width arithmetic.

    Constants vary with the index so the bodies are not identical, giving the
    checker and the optimizer non-degenerate work per function.
    """
    k1 = 7 + (i * 13) % 101
    k2 = 3 + (i * 29) % 97
    k3 = 1 + (i * 17) % 89
    return f"""fun {name}{i}(a: int64, b: int64) -> int64 {{
    let acc = a + {k1}
    let t = 0
    while t < 6 {{
        if acc % 2 == 0 {{
            acc = (acc * 3 + b + {k2}) % 1000003
        }} else {{
            acc = (acc / 2 + t * {k3}) % 999983
        }}
        t += 1
    }}
    return acc
}}
"""


def gen_wide_cold_unused():
    parts = [
        "// GENERATED by gen_cases.py -- do not edit by hand.\n"
        "// Wide cold-start program: %d top-level functions, but main calls only\n"
        "// one of them. Eager must check and compile the whole module up front;\n"
        "// lazy only needs the reached function ready before main runs, so this\n"
        "// is the best case for lazy cold start.\n\n" % WIDE_FNS
    ]
    for i in range(WIDE_FNS):
        parts.append(wide_fn("w", i))
    parts.append(
        "\nfun main() {\n"
        '    println("begin")\n'
        '    println("w0 = {w0(11, 22)}")\n'
        "}\n"
    )
    with open(os.path.join(CASES, "02_wide_cold_unused.cz"), "w") as f:
        f.write("\n".join(parts))


def gen_wide_all_called():
    parts = [
        "// GENERATED by gen_cases.py -- do not edit by hand.\n"
        "// Wide fully-used program: %d top-level functions, each called exactly\n"
        "// once from main. Every function must be checked AND compiled in both\n"
        "// modes, so this measures the per-function overhead of on-demand\n"
        "// materialization against one whole-module compile.\n\n" % WIDE_FNS
    ]
    for i in range(WIDE_FNS):
        parts.append(wide_fn("v", i))
    main = ["\nfun main() {", '    println("begin")', "    let sum: int64 = 0"]
    for i in range(WIDE_FNS):
        main.append(f"    sum = (sum + v{i}({i}, {(i * 7) % 97})) % 1000000007")
    main.append('    println("checksum = {sum}")')
    main.append("}")
    parts.append("\n".join(main) + "\n")
    with open(os.path.join(CASES, "03_wide_all_called.cz"), "w") as f:
        f.write("\n".join(parts))


def gen_infer_chain():
    parts = [
        "// GENERATED by gen_cases.py -- do not edit by hand.\n"
        "// Deep unannotated-return call chain (depth %d): every return type\n"
        "// must be inferred from the next callee, which is what the checker's\n"
        "// deferred-instance machinery resolves. A second, never-called chain\n"
        "// of the same depth measures how much unreached definitions cost.\n"
        "// The chain is int32 on purpose: an int64 chain deeper than 64 makes\n"
        "// the lazy pipeline abort (deferred call sites beyond that depth are\n"
        "// compiled assuming the default int32 return and cannot adapt when\n"
        "// the resolution comes back int64); eager accepts any depth.\n\n"
        % CHAIN_LEN
    ]
    # The called chain: c0 -> c1 -> ... -> c<last>.
    for i in range(CHAIN_LEN - 1):
        parts.append(f"fun c{i}(x: int32) {{\n    return c{i + 1}(x) + 1\n}}\n")
    parts.append(f"fun c{CHAIN_LEN - 1}(x: int32) {{\n    return x\n}}\n")
    # The unreached chain: u0 -> u1 -> ... never called from main.
    for i in range(CHAIN_LEN - 1):
        parts.append(f"fun u{i}(x: int32) {{\n    return u{i + 1}(x) + 2\n}}\n")
    parts.append(f"fun u{CHAIN_LEN - 1}(x: int32) {{\n    return x\n}}\n")
    parts.append(
        "\nfun main() {\n"
        '    println("begin")\n'
        '    println("chain = {c0(1)}")\n'
        "}\n"
    )
    with open(os.path.join(CASES, "06_infer_chain.cz"), "w") as f:
        f.write("\n".join(parts))


def gen_mono_heavy():
    """Many distinct generic instantiations, each exercised lightly."""
    key_types = [
        ("i32", ["1", "2", "3"], "0"),
        ("i64", ["10000000001", "10000000002", "10000000003"], "0"),
        ("str", ['"ka"', '"kb"', '"kc"'], '"kd"'),
    ]
    val_types = [
        ("i32", ["11", "12", "13"], "0"),
        ("i64", ["20000000001", "20000000002", "20000000003"], "0"),
        ("f64", ["1.5", "2.5", "3.5"], "0.0"),
        ("str", ['"va"', '"vb"', '"vc"'], '"vd"'),
    ]
    parts = [
        "// GENERATED by gen_cases.py -- do not edit by hand.\n"
        "// Monomorphization breadth: one function per HashMap key/value type\n"
        "// combination plus per-element-type array combinator use. All of them\n"
        "// are reached from main, so both modes instantiate every combination;\n"
        "// this measures scheme instantiation and per-instance codegen cost.\n\n"
    ]
    names = []
    for kt, keys, _kd in key_types:
        for vt, vals, vd in val_types:
            name = f"map_{kt}_{vt}"
            names.append(name)
            body = [f"fun {name}() -> int64 {{", "    let m = HashMap.new()"]
            for k, v in zip(keys, vals):
                body.append(f"    m.set({k}, {v})")
            # Convert the read-back value to an int64 score without needing
            # type-specific operations: compare against the stored value.
            if vt == "f64":
                probe = f"if m.get_or({keys[0]}, {vd}) > 1.0 {{ 1 }} else {{ 0 }}"
            elif vt == "str":
                probe = f"if m.get_or({keys[0]}, {vd}) == {vals[0]} {{ 1 }} else {{ 0 }}"
            else:
                probe = f"m.get_or({keys[0]}, {vd})"
            body.append(f"    let probe: int64 = {probe}")
            body.append("    return probe + m.size()")
            body.append("}")
            parts.append("\n".join(body) + "\n")
    # Array combinators at several element types.
    parts.append(
        "fun arr_i32() -> int64 {\n"
        "    let a = [3, 1, 4, 1, 5, 9, 2, 6]\n"
        "    return a.filter((x) -> x > 2).map((x) -> x * 3).fold(0, (s, x) -> s + x)\n"
        "}\n"
    )
    parts.append(
        "fun arr_i64() -> int64 {\n"
        "    let a: int64[] = [30000000000, 1, 4, 1, 5]\n"
        "    return a.fold(0, (s, x) -> s + x) % 1000000007\n"
        "}\n"
    )
    parts.append(
        "fun arr_f64() -> int64 {\n"
        "    let a = [1.5, 2.5, 3.5, 4.5]\n"
        "    let s = a.map((x) -> x * 2.0).fold(0.0, (t, x) -> t + x)\n"
        "    return if s > 20.0 { 1 } else { 0 }\n"
        "}\n"
    )
    names += ["arr_i32", "arr_i64", "arr_f64"]
    main = ["\nfun main() {", '    println("begin")', "    let sum: int64 = 0"]
    for n in names:
        main.append(f"    sum += {n}()")
    main.append('    println("checksum = {sum}")')
    main.append("}")
    parts.append("\n".join(main) + "\n")
    with open(os.path.join(CASES, "07_mono_heavy.cz"), "w") as f:
        f.write("\n".join(parts))


def gen_big_main():
    parts = [
        "// GENERATED by gen_cases.py -- do not edit by hand.\n"
        "// One huge main body (%d generated statements). main always runs, so\n"
        "// neither pipeline can defer any of this; measures how both handle a\n"
        "// single oversized function (check + LLVM opt/isel of one big body).\n\n"
        % BIG_MAIN_STMTS,
        "fun main() {",
        '    println("begin")',
        "    let v = 12345",
    ]
    for i in range(BIG_MAIN_STMTS):
        k = 3 + (i * 31) % 211
        if i % 40 == 17:
            parts.append(
                f"    if v % 3 == 0 {{ v = (v * 2 + {k}) % 999983 }}"
                f" else {{ v = (v + {k}) % 1000003 }}"
            )
        elif i % 100 == 51:
            parts.append(
                f"    let t{i} = 0\n"
                f"    while t{i} < 3 {{\n"
                f"        v = (v * 5 + t{i} + {k}) % 999979\n"
                f"        t{i} += 1\n"
                f"    }}"
            )
        else:
            parts.append(f"    v = (v * 7 + {k}) % 1000033")
    parts.append('    println("checksum = {v}")')
    parts.append("}")
    with open(os.path.join(CASES, "09_big_main.cz"), "w") as f:
        f.write("\n".join(parts) + "\n")


if __name__ == "__main__":
    gen_wide_cold_unused()
    gen_wide_all_called()
    gen_infer_chain()
    gen_mono_heavy()
    gen_big_main()
    print("regenerated cases in", CASES)
