//! Embeds the core library. The `core/` tree is enumerated at build time and
//! written to `$OUT_DIR/stdlib.rs` as one table of
//! `(module key, include_str!(source))` pairs:
//!
//! - `STDLIB` -- every `.cz` under `core/`, keyed by its `core/`-relative
//!   path without the extension (`io`, `array`, `collections`, ...). Every
//!   entry is part of the implicit prelude: its public names are in scope in
//!   every program with no import.
//!
//! `loader.rs` pulls the table in with `include!`, so adding a module to the
//! core library is just adding a file -- no Rust edit. The generated
//! `include_str!` paths are anchored at `CARGO_MANIFEST_DIR` (they cannot be
//! relative: a relative path inside the generated file would resolve against
//! `OUT_DIR`), and they make the compiler re-embed a module when its source
//! changes; this script itself re-runs only when the tree's shape changes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Every `.cz` under `dir` (recursively), as the pair of its `root`-relative
/// extensionless key and its `include_base`-relative include path (the repo
/// root, so paths read `core/...`), sorted by key so the generated table is
/// deterministic.
fn collect_cz(root: &Path, include_base: &Path, dir: &Path) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for entry in fs::read_dir(&d).expect("read core dir") {
            let path = entry.expect("read core dir entry").path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "cz") {
                let key = path
                    .strip_prefix(root)
                    .expect("under root")
                    .with_extension("")
                    .to_string_lossy()
                    .replace('\\', "/");
                let include = path
                    .strip_prefix(include_base)
                    .expect("under the repo root")
                    .to_string_lossy()
                    .replace('\\', "/");
                out.push((key, include));
            }
        }
    }
    out.sort();
    out
}

fn write_table(out: &mut String, name: &str, doc: &str, entries: &[(String, String)]) {
    for line in doc.lines() {
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(&format!("pub const {name}: &[(&str, &str)] = &[\n"));
    for (key, include) in entries {
        out.push_str(&format!(
            "    ({key:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../{include}\"))),\n"
        ));
    }
    out.push_str("];\n");
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let core_dir = manifest.join("../../core");
    // Adding/removing/renaming a module re-runs this script (cargo scans the
    // directory); editing one only recompiles through include_str!.
    println!("cargo:rerun-if-changed={}", core_dir.display());

    let repo_root = core_dir.parent().expect("core has a parent").to_path_buf();
    let modules = collect_cz(&core_dir, &repo_root, &core_dir);
    assert!(
        !modules.is_empty(),
        "no core modules found under {}",
        core_dir.display()
    );

    let mut src = String::new();
    write_table(
        &mut src,
        "STDLIB",
        "Embedded core-library modules (every `.cz` under `core/`), always in\n\
         scope with no import needed: together they are the implicit prelude.\n\
         Keyed by the module's `core/`-relative path without the extension\n\
         (segments joined with `/`). Generated by build.rs from the `core/`\n\
         tree.",
        &modules,
    );

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("stdlib.rs");
    fs::write(&out, src).expect("write stdlib.rs");
}
